services:
  floci-az:
    build:
      context: .
      dockerfile: docker/Dockerfile.native
    ports:
      - "4577:4577"
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    tty: true
    environment:
      FLOCI_AZ_STORAGE_MODE: memory
      FLOCI_AZ_SERVICES_DOCKER_NETWORK: floci_az_default
      FLOCI_AZ_TLS_ENABLED: "true"
      FLOCI_AZ_HOSTNAME: floci-az
    networks:
      floci_az_default:
        aliases:
          - floci-az

networks:
  floci_az_default:
    name: floci_az_default
