services:
  floci-az:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "4577:4577"
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    tty: true
    environment:
      FLOCI_AZ_STORAGE_MODE: memory
      FLOCI_AZ_SERVICES_DOCKER_NETWORK: floci_az_default
    networks:
      floci_az_default:
        aliases:
          - floci-az

networks:
  floci_az_default:
    name: floci_az_default
